runtime: python27
threadsafe: true
api_version: 1
basic_scaling:
  max_instances: 2

#[START_EXCLUDE]
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?setuptools/script \(dev\).tmpl$
- ^(.*/)?.*/bower_components/.*$
- ^(.*/)?.*/node_modules/.*$
#[END_EXCLUDE]

handlers:
# The endpoints handler must be mapped to /_ah/api.
- url: /_ah/api/.*
  script: main.api

- url: /styles
  static_dir: ga-front/dist/styles

- url: /scripts
  static_dir: ga-front/dist/scripts

- url: /images
  static_dir: ga-front/dist/images

- url: /fonts
  static_dir: ga-front/dist/fonts

- url: .*
  script: main.app

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11

# [START env_vars]
env_variables:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy swagger.json' command.
  ENDPOINTS_SERVICE_NAME: ga-hs-test.appspot.com
  ENDPOINTS_SERVICE_VERSION: 2017-11-22r2
 # [END env_vars]